spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/records?setUnicode=true&characterEncoding=utf8&useAffectedRows=true
    username: root
    password: 317429722
  servlet:
    multipart:
      max-file-size: 30Mb
      max-request-size: 30Mb


mybatis:
  type-aliases-package: com.wdd.studentmanager.domain
  mapper-locations: classpath:mapper/*.xml

